site_name: Enterprise Solution Architecture (ESA) Model

nav:
  - Introduction: index.md
  - Element List: esa-element-list.md
  - Element Definition: esa-element-definition.md
  - Base Model Elements: esa-base-elements.md
  - Lean Mode Elements: esa-lean-mode-elements.md
  - EA Elements: esa-ea-profile-elements.md
  - SW Design Elements: esa-swd-profile-elements.md
  - SW Arch Elements: esa-swa-profile-elements.md
  - AI Elements: esa-ai-solution-elements.md
  - Integration Elements: esa-is-elements.md
  - BA Elements: esa-business-arch-elements.md
  - Infra Elements: esa-infra-arch-elements.md
  - FAQs: esa-faq.md

theme:
  name: material
